services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      POSTGRES_USER: ${MYSQL_USER}
      POSTGRES_DB: ${MYSQL_DATABASE}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - backend

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node_container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - ./node/src:/app
      - ./logs/node:/app/logs
    depends_on:
      - db
    networks:
      - backend
    command: sh -c "npm install && npm start"

networks:
  backend:
    driver: bridge